language: node_js

build:
  ci:
    - ls $SHIPPABLE_BUILD_DIR
    - TRANSFER=$(shipctl get_resource_state sample_node_runCI)
    - echo "Writing to $TRANSFER"
    - tar -cvf sample_node_repo.tar $SHIPPABLE_BUILD_DIR
    - sha1sum sample_node_repo.tar
    - stat sample_node_repo.tar


jobs:
  - name: sample_node_runCI
    type: runCI
    steps: []

  - name: read_tar_file
    type: runSh
    steps:
      - IN: sample_node_runCI
        switch: on
      - IN: sample_node_ciRepo
        switch: off
      - TASK:
          script:
            - TRANSFER=$(shipctl get_resource_state sample_node_runCI)
            - echo "Reading from $TRANSFER"
            - sha1sum $TRANSFER/sample_node_repo.tar      
            - stat $TRANSFER/sample_node_repo.tar
