language: node_js

node_js:
  - 4.8.7

runtime:
  nodePool: default_cluster


build:
  ci:
    - echo true1
    - printenv

#integrations:
#  notifications: 
#    - integrationName: email
#      type: email
#      recipients:
#        - ankul@shippable.com
#      on_success: always
#  hub:
#    - integrationName: docker-shared-subint
#      type: dockerRegistryLogin
#  generic:
#    - integrationName: kv-shared-subint 

resources:
  - name: sample_c	
    type: gitRepo	
    integration: "github-subint"	
    versionTemplate:	
      sourceName: ankul-shippable/sample_c
      branch: master
      
  - name: trigger	
    type: time		
    versionTemplate:	
      interval: "*/3 * * * *"

jobs:
  - name: sample_c_runCI
    type: runCI
    steps:
      - IN: trigger

      
#  - name: runSh-job
#    type: runSh
#    runtime:
#      nodePool: default_cluster
#    steps:
#      - OUT: sample_c_ciRepo
#        replicate: sample_c
#      - TASK:
#          script:
#            - printenv
