language: node_js

env:
  global:
    - FOO=FUBU_4

  matrix:
    - M1=ONE  

build:
  pre_ci:
    - echo "true_8"

  ci:
    - if [ "$(($BUILD_NUMBER % 2))" -eq 0 ]; then failing it; fi # fail if build number is even
    - printenv
    
  post_ci:
    - echo "true"

jobs:
  - name: sample_runSh
    type: runSh
    steps:
      - TASK:
          name: print file tree
          script: sudo apt-get install tree && tree

#integrations:
#  notifications:
#    - integrationName: email
#      type: email
#      recipients:
#        - ankul@shippable.com
#        - ankulkumar001@gmail.com
#        - mabcd71@gmail.com
#      on_success: always
#
#    - integrationName: irc
#      type: irc
#      recipients:
#        - "chat.quakenet.org#randyorton"
#      on_success: always
#
#integrations:
#  notifications:
#    - integrationName: resource-trigger-subint
#      type: webhook
#      payload:
#      - versionName=Shippable nginx-image-2 $BUILD_NUMBER
#      on_success: always
#      on_start: never
#      on_pull_request: always

#    - integrationName: resource-trigger-subint-2
#      type: webhook
#      payload:
#      - versionName=Shippable nginx-image-3 $BUILD_NUMBER
#      on_success: always
#      on_start: never
#      on_pull_request: always
