language: node_js

node_js:
  - 4.8.7

runtime:
  nodePool: default_cluster

env:
  global:
    - FOO=FUBU

  matrix:
    - M1=ONE
    - M2=TWO

build:
  ci:
    - echo true1
    - printenv

#integrations:
#  notifications: 
#    - integrationName: email
#      type: email
#      recipients:
#        - ankul@shippable.com
#      on_success: always
#  hub:
#    - integrationName: docker-shared-subint
#      type: dockerRegistryLogin
#  generic:
#    - integrationName: kv-shared-subint 

resources:
  - name: time	
    type: time	
    versionTemplate:	
      interval: "*/7 * * * *"
      

jobs: 
  - name: sample_node_runCI
    type: runCI
    steps:
      - IN: time
#        replicate: sample_c
#      - TASK:
#          script:
#            - printenv
