language: node_js

node_js:
  - 4.8.7

runtime:
  nodePool: default_cluster


build:
  ci:
    - echo true
    - printenv

integrations:
  notifications: 
    - integrationName: slack-subint
      type: slackKey
      recipients:
        - "#test-5148"
      on_start: always
  hub:
    - integrationName: docker-subint
      type: dockerRegistryLogin
  generic:
    - integrationName: kv-subint   

resources:
  - name: nginx-image-shared
    type: image
    integration: "docker-shared-subint"
    versionTemplate:
      sourceName: "ankul/app"
      versionName: latest

  - name: repo-resource-shared
    type: gitRepo
    integration: "github-shared-subint"
    versionTemplate:
      sourceName: "ankul-shippable/sample_java"
      branch: "master"

  - name: nginx-image
    type: image
    integration: "docker-subint"
    versionTemplate:
      sourceName: "ankul/app"
      versionName: latest

  - name: repo_resource
    type: gitRepo
    integration: "github-subint"
    versionTemplate:
      sourceName: "ankul-shippable/sample_java"
      branch: "master"

  - name: docker-shared-res
    type: integration
    integration: "docker-shared-subint" 
    
  - name: ssh-shared-res
    type: integration
    integration: "ssh-shared-subint"    
    
  - name: docker-res
    type: integration
    integration: "docker-subint" 
    
  - name: ssh-res
    type: integration
    integration: "ssh-subint"        

jobs:
  - name: manifest-job-shared
    type: manifest
    steps:
      - IN: nginx-image-shared

  - name: runSh-shared-indirect
    type: runSh
    runtime:
      nodePool: default_cluster
    steps:
      - IN: manifest-job-shared
      - IN: docker-shared-res
      - IN: ssh-shared-res
      - TASK:
          script:
            - echo ================ docker-shared-res ==================
            - shipctl get_integration_resource_keys "docker-shared-res"
            - shipctl get_integration_resource_field "docker-shared-res" "url"
            - echo ================ ssh-shared-res ==================
            - shipctl get_integration_resource_keys ssh-shared-res
            - shipctl get_integration_resource_field ssh-shared-res publicKey
            - shipctl get_integration_resource_field ssh-shared-res privateKey

  - name: runSh-shared-direct
    type: runSh
    runtime:
      nodePool: default_cluster
    integrations:
      - docker-shared-subint
      - ssh-shared-subint
    steps:
      - IN: manifest-job-shared
      - TASK:
          script:
            - echo ================ docker-shared-subint ==================
            - shipctl get_integration_keys docker-shared-subint
            - shipctl get_integration_field docker-shared-subint url
            - echo ================ ssh-shared-subint ==================
            - shipctl get_integration_keys ssh-shared-subint
            - shipctl get_integration_field ssh-shared-subint publicKey
            - shipctl get_integration_field ssh-shared-subint privateKey


  - name: runSh-direct
    type: runSh
    runtime:
      nodePool: default_cluster
    integrations:
      - docker-subint
      - ssh-subint
    steps:
      - IN: manifest-job-shared
      - TASK:
          script:
            - echo ================ docker-subint ==================
            - shipctl get_integration_keys docker-subint
            - shipctl get_integration_field docker-subint url
            - echo ================ ssh-subint ==================
            - shipctl get_integration_keys ssh-subint
            - shipctl get_integration_field ssh-subint publicKey
            - shipctl get_integration_field ssh-subint privateKey
