language: node_js

node_js:
  - 4.8.7

#runtime:
#  nodePool: default_cluster


build:
  ci:
    - echo true

resources:
  - name: nginx-image
    type: image
    integration: "docker-subint"
    pointer:
      sourceName: "ankul/app"
    seed:
      versionName: latest

  - name: docker-int-res
    type: integration
    integration: "docker-subint"

  - name: key-value-int-res
    type: integration
    integration: "key-value-subint"  

  - name: ssh-int-res
    type: integration
    integration: "ssh-subint"

  - name: nodes-int-res
    type: integration
    integration: "nodes-subint"  
  - name: trigger_nightly
    type: time
    versionTemplate:
      interval: "* 22 * * *"

jobs:
  - name: sample_node_runCI
    type: runCI
    steps:
      - IN: trigger_nightly

  - name: runSh
    type: runSh
    runtime:
      nodePool: custom_one
    steps:
      - IN: nginx-image
      - IN: trigger_nightly
      - TASK:
          script:
            - printenv

  - name: manifest-job
    type: manifest
    steps:
      - IN: nginx-image

  - name: indirect_integrations
    type: runSh
    runtime:
      nodePool: custom_one
    steps:
      - IN: nginx-image
      - IN: manifest-job
      - IN: docker-int-res
      - IN: key-value-int-res
      - IN: ssh-int-res
      - IN: nodes-int-res
      - TASK:
          script:
            - apt-get install tree
            - tree $JOB_PATH
            - printenv
            - GIT_SSH_COMMAND='ssh -i $SSHINTRES_PRIVATE_KEY_PATH' git clone git@github.com:ankul-shippable/sample_node.git && ls
            - echo ================ docker-int-res ==================
            - shipctl get_integration_resource_keys "docker-int-res"
            - shipctl get_integration_resource_field "docker-int-res" "url"
            - echo ================ ssh-int-res ==================
            - shipctl get_integration_resource_keys ssh-int-res
            - shipctl get_integration_resource_field ssh-int-res publicKey
            - shipctl get_integration_resource_field ssh-int-res privateKey
            - echo ================ nodes-int-res ==================
            - shipctl get_integration_resource_keys nodes-int-res
            - shipctl get_integration_resource_field nodes-int-res nodes
            - echo ================ key-value-int-res ==================
            - shipctl get_integration_resource_keys key-value-int-res
            - shipctl get_integration_resource_field key-value-int-res SOME_RANDOM_ENV_2

  - name: direct_integrations
    type: runSh
    runtime:
      nodePool: custom_one
    integrations:
      - docker-subint
      - key-value-subint
      - ssh-subint
      - nodes-subint
    steps:
      - IN: docker-int-res
      - IN: nginx-image
      - IN: manifest-job
      - TASK:
          script:        
            - apt-get install tree
            - tree $JOB_PATH
            - printenv
            - GIT_SSH_COMMAND='ssh -i $SSHSUBINT_PRIVATE_KEY_PATH' git clone git@github.com:ankul-shippable/sample_node.git && ls
            - echo ================ docker-subint ==================
            - shipctl get_integration_keys docker-subint
            - shipctl get_integration_field docker-subint url
            - echo ================ ssh-subint ==================
            - shipctl get_integration_keys ssh-subint
            - shipctl get_integration_field ssh-subint publicKey
            - shipctl get_integration_field ssh-subint privateKey
            - echo ================ nodes-subint ==================
            - shipctl get_integration_keys nodes-subint
            - shipctl get_integration_field nodes-subint nodes
            - echo ================ key-value-subint ==================
            - shipctl get_integration_keys key-value-subint
            - shipctl get_integration_field key-value-subint SOME_RANDOM_ENV_2

  - name: windows_indirect_integrations
    type: runSh
    runtime:
      nodePool: custom_windows
    steps:
      - IN: nginx-image
      - IN: manifest-job
      - IN: docker-int-res
      - IN: key-value-int-res
      - IN: ssh-int-res
      - IN: nodes-int-res
      - TASK:
          script:
            #- SET
            #- GIT_SSH_COMMAND='ssh -i $SSHINTRES_PRIVATE_KEY_PATH' git clone git@github.com:ankul-shippable/sample_node.git && ls
            - echo ================ docker-int-res ==================
            - shipctl get_integration_resource_keys "docker-int-res"
            - shipctl get_integration_resource_field "docker-int-res" "url"
            - echo ================ ssh-int-res ==================
            - shipctl get_integration_resource_keys ssh-int-res
            - shipctl get_integration_resource_field ssh-int-res publicKey
            - shipctl get_integration_resource_field ssh-int-res privateKey
            - echo ================ nodes-int-res ==================
            - shipctl get_integration_resource_keys nodes-int-res
            - shipctl get_integration_resource_field nodes-int-res nodes
            - echo ================ key-value-int-res ==================
            - shipctl get_integration_resource_keys key-value-int-res
            - shipctl get_integration_resource_field key-value-int-res SOME_RANDOM_ENV_2

  - name: windows_direct_integrations
    type: runSh
    runtime:
      nodePool: custom_windows
    integrations:
      - docker-subint
      - key-value-subint
      - ssh-subint
      - nodes-subint
    steps:
      - IN: docker-int-res
      - IN: nginx-image
      - IN: manifest-job
      - TASK:
          script:       
            #- SET
            #- GIT_SSH_COMMAND='ssh -i $SSHSUBINT_PRIVATE_KEY_PATH' git clone git@github.com:ankul-shippable/sample_node.git && ls
            - echo ================ docker-int-res ==================
            - shipctl get_integration_resource_keys "docker-int-res"
            - shipctl get_integration_resource_field "docker-int-res" "url"
            - echo ================ docker-subint ==================
            - shipctl get_integration_keys docker-subint
            - shipctl get_integration_field docker-subint url
            - echo ================ ssh-subint ==================
            - shipctl get_integration_keys ssh-subint
            - shipctl get_integration_field ssh-subint publicKey
            - shipctl get_integration_field ssh-subint privateKey
            - echo ================ nodes-subint ==================
            - shipctl get_integration_keys nodes-subint
            - shipctl get_integration_field nodes-subint nodes
            - echo ================ key-value-subint ==================
            - shipctl get_integration_keys key-value-subint
            - shipctl get_integration_field key-value-subint SOME_RANDOM_ENV_2

  - name: no_ints
    type: runSh
    runtime:
      nodePool: custom_one
    steps:
      - IN: nginx-image
      - IN: manifest-job
      - TASK:
          script:
            - printenv
