language: node_js

node_js: 4.8.7

runtime:
  nodePool: default_cluster

env:
  global:
    - secure: PHdYfWHv+a7/a4M0kHS5NxZbZMDwn3BFtNZnQdSEnYcfvrjHhFT8v+4NBb4lhEJEPX3Cmz7Rcxz0+Sh/GKTcBu9Zu3MjBemNiyV3LgMXaaBTWCk/nBQCskzNvGoCUg/615RJsw7aCYAyQmhmtoZgJwt3WhmYvt5Y7ytIx4wQawz3PUe1woaXBgXou96D48KWiSwLm0oLDYG5zBDMM8aswwk1+mEH22t8LD7EimdEqbBVhEmdMGNqpYDrdSFsRBsDhU4DyDgS9iowFdFuyb7EDpNNKIzFXpi1WdNsnzQe+AFlZjQCeMbmFQFKVCmxxnpuhoddvJBmGGKiePfQlydeDw==
  matrix:
    - foo: bar 
    - foo: fizz

build:
  ci:
    - printenv

#integrations:
#  notifications: 
#    - integrationName: email
#      type: email
#      recipients:
#        - ankul@shippable.com
#      on_success: always
#  hub:
#    - integrationName: docker-shared-subint
#      type: dockerRegistryLogin
#  generic:
#    - integrationName: kv-shared-subint 

resources:
  - name: time	
    type: time	
    versionTemplate:	
      interval: "*/30 * * * *"
      

jobs: 
  - name: sample_node_runCI
    type: runCI
    steps:
      - IN: time
      - TASK:
          script:
            - printenv
            
  - name: sample_ruby_runCI
    type: runCI
    steps:
      - IN: time
      - TASK:
          script:
            - printenv
