language: node_js

env:
  global:
    - FOO=FUBU_5

  matrix:
    - M1=ONE

build:
  pre_ci:
    - echo "true_8"

  ci:
    #- if [ "$(($BUILD_NUMBER % 2))" -eq 0 ]; then failing it; fi # fail if build number is even
    - echo "true_ci_7"
    - printenv

  post_ci:
    - echo "true"


integrations:
  notifications:
    - integrationName: "webhook-subint"
      type: webhook
      payload:
        - state=$STATE
        - repo_name=$REPO_FULL_NAME
        - branch=$BRANCH
        - build_number=$BUILD_NUMBER
        - build_url=$BUILD_URL
        - commit_message=$COMMIT_MESSAGE
        - committer=$COMMITTER
        - is_success=$is_success
        - displayName=Shippable
        - avatar=https://app.shippable.com/images/slack-aye-aye-yoga.png
      on_start: always
      on_success: always

#    - integrationName: resource-trigger-subint-2
#      type: webhook
#      payload:
#      - versionName=Shippable nginx-image-3 $BUILD_NUMBER
#      on_success: always
#      on_start: never
#      on_pull_request: always

jobs:
  - name: sample_runSh
    type: runSh
    runtime:
      nodePool: random_nodes
    steps:
      - TASK:
          name: print file tree
          script: sudo apt-get install tree && tree
    on_success:
      script:
        - echo "SUCCESS"
        - tree

  - name: sample_runSh_2
    type: runSh
    runtime:
      nodePool: random_nodes
    steps:
      - TASK:
          name: print file tree
          script: sudo apt-get install tree && tree
    on_success:
      - script: echo 'this is on_success step of dv-man of type manifest'

  - name: sample_runSh_3
    type: runSh
    runtime:
      nodePool: random_nodes
    steps:
      - TASK:
          name: print file tree
          script: sudo apt-get install tree && tree
    on_success: STRING
