language: node_js

build:
  ci:
    - apt-get install tree
    - ls -al $SHIPPABLE_BUILD_DIR
    - TRANSFER=$(shipctl get_resource_state sample_node_runCI)
    - tree $TRANSFER
    - echo "Writing to $TRANSFER"
    - tar cvf --exclude $SHIPPABLE_BUILD_DIR".*" $TRANSFER/sample_node_repo.tar $SHIPPABLE_BUILD_DIR
    - tree $TRANSFER
    - sha1sum $TRANSFER/sample_node_repo.tar
    - stat $TRANSFER/sample_node_repo.tar
    - du -h $TRANSFER

jobs:
  - name: sample_node_runCI
    type: runCI
    steps: []

  - name: read_tar_file
    type: runSh
    steps:
      - IN: sample_node_runCI
        switch: on
      - IN: sample_node_ciRepo
        switch: off
      - TASK:
          script:
            - TRANSFER=$(shipctl get_resource_state sample_node_runCI)
            - echo "Reading from $TRANSFER"
            - sha1sum $TRANSFER/sample_node_repo.tar      
            - stat $TRANSFER/sample_node_repo.tar
