language: node_js

node_js:
  - 4.8.7

build:
  ci:
    - apt-get install tree
    - TRANSFER=$(shipctl get_resource_state sample_node_runCI)
    - tree $TRANSFER
    - echo "Writing to $TRANSFER"
    - cd $SHIPPABLE_BUILD_DIR && rm -rf .git && cd -
    - tar cvf $TRANSFER/sample_node_repo.tar $SHIPPABLE_BUILD_DIR
    - shipctl post_resource_state sample_node_runCI "HERO" "Superman"
    - shipctl put_resource_state sample_node_runCI "SUPERHERO" "batman"    
    - ls -al $SHIPPABLE_BUILD_DIR
    - tree $TRANSFER
    - sha1sum $TRANSFER/sample_node_repo.tar
    - stat $TRANSFER/sample_node_repo.tar
    - du -h $TRANSFER

jobs:
  - name: sample_node_runCI
    type: runCI
    steps: []

  - name: read_tar_file
    type: runSh
    steps:
      - IN: sample_node_runCI
        switch: on
      - IN: sample_node_ciRepo
        switch: off
      - TASK:
          script:
            - TRANSFER=$(shipctl get_resource_state sample_node_runCI)
            - echo "Reading from $TRANSFER"
            - sha1sum $TRANSFER/sample_node_repo.tar 
            - stat $TRANSFER/sample_node_repo.tar
            - cat $TRANSFER/sample_node_runCI.env
