language: node_js

node_js:
  - 4.8.7

#runtime:
#  nodePool: default_cluster


build:
  ci:
    - echo true

resources:
  - name: nginx-image
    type: image
    integration: "docker-subint"
    pointer:
      sourceName: "ankul/app"
    seed:
      versionName: latest

jobs:
  - name: sample_c_runCI
    type: runCI
    steps:
      - OUT: nginx-image
    
  - name: runSh
    type: runSh
    runtime:
      nodePool: default_cluster
    steps:
      - IN: nginx-image
      - TASK:
          script:
            - printenv
