language: node_js

node_js:
  - 4.8.7

build:
  ci:
    - echo $PREVIOUS_VERSION_NAME
    - echo $RANOM_TEST_ENV
    - shipctl put_resource_state_multi "$JOB_NAME" "PREVIOUS_VERSION_NAME=build_$BUILD_NUMBER" "RANOM_TEST_ENV=test_$BUILD_NUMBER"

jobs:
  - name: test-job
    type: runSh
    steps:
      - TASK:
        - script: echo $PREVIOUS_VERSION_NAME
        - script: echo $RANOM_TEST_ENV
        - script: shipctl put_resource_state_multi "$JOB_NAME" "PREVIOUS_VERSION_NAME=build_$BUILD_NUMBER" "RANOM_TEST_ENV=test_$BUILD_NUMBER"
