jobs:
  - name: runSh-Job-1_sample_node
    type: runSh
    steps:
      - IN: runSh-Job-2
      - TASK:
        - script: sudo apt-get install tree
        - script: tree -F IN
        - script: sleep 3
    on_success:
      - script: echo "successfully completed"
      
  - name: runSh-Job-2_sample_node
    type: runSh
    steps:
      - TASK:
        - script: sudo apt-get install tree
        - script: tree -F IN
        - script: sleep 3
    on_success:
      - script: echo "successfully completed"      
