language: node_js

node_js:
  - 4.8.7

#runtime:
#  nodePool: default_cluster


build:
  ci:
    - echo true

resources:
  - name: nginx-image-shared
    type: image
    integration: "docker-shared-subint"
    versionTemplate:
      sourceName: "ankul/app"
      versionName: latest

  - name: repo-resource-shared
    type: gitRepo
    integration: "github--shared-subint"
    versionTemplate:
      sourceName: "ankul-shippable/sample_java"
      branch: "master"

  - name: nginx-image
    type: image
    integration: "docker-subint"
    versionTemplate:
      sourceName: "ankul/app"
      versionName: latest

  - name: repo_resource
    type: image
    integration: "github--subint"
    versionTemplate:
      sourceName: "ankul-shippable/sample_java"
      branch: "master"

  - name: docker-shared-res
    type: image
    integration: "docker-shared-subint" 
    
  - name: ssh-shared-res
    type: image
    integration: "ssh-shared-subint"    
    
  - name: docker-res
    type: image
    integration: "docker-shared-subint" 
    
  - name: ssh-res
    type: image
    integration: "ssh-shared-subint"        

jobs:
  - name: manifest-job-shared
    type: manifest
    steps:
      - IN: nginx-image-shared

  - name: runSh-shared-indirect
    type: runSh
    runtime:
      nodePool: custom_one
    steps:
      - IN: manifest-job-shared
      - IN: docker-shared-res
      - IN: ssh-shared-res
      - TASK:
          script:
            - echo ================ docker-int-res ==================
            - shipctl get_integration_resource_keys "docker-shared-res"
            - shipctl get_integration_resource_field "docker-shared-res" "url"
            - echo ================ ssh-int-res ==================
            - shipctl get_integration_resource_keys ssh-shared-res
            - shipctl get_integration_resource_field ssh-shared-res publicKey
            - shipctl get_integration_resource_field ssh-shared-res privateKey

  - name: direct_integrations
    type: runSh
    runtime:
      nodePool: custom_one
    integrations:
      - docker-subint
      - key-value-subint
      - ssh-subint
      - nodes-subint
    steps:
      - IN: docker-int-res
      - IN: nginx-image
      - IN: manifest-job
      - TASK:
          script:        
            - apt-get install tree
            - tree $JOB_PATH
            - printenv
            - GIT_SSH_COMMAND='ssh -i $SSHSUBINT_PRIVATE_KEY_PATH' git clone git@github.com:ankul-shippable/sample_node.git && ls
            - echo ================ docker-subint ==================
            - shipctl get_integration_keys docker-subint
            - shipctl get_integration_field docker-subint url
            - echo ================ ssh-subint ==================
            - shipctl get_integration_keys ssh-subint
            - shipctl get_integration_field ssh-subint publicKey
            - shipctl get_integration_field ssh-subint privateKey
            - echo ================ nodes-subint ==================
            - shipctl get_integration_keys nodes-subint
            - shipctl get_integration_field nodes-subint nodes
            - echo ================ key-value-subint ==================
            - shipctl get_integration_keys key-value-subint
            - shipctl get_integration_field key-value-subint SOME_RANDOM_ENV_2

  - name: windows_indirect_integrations
    type: runSh
    runtime:
      nodePool: custom_windows
    steps:
      - IN: nginx-image
      - IN: manifest-job
      - IN: docker-int-res
      - IN: key-value-int-res
      - IN: ssh-int-res
      - IN: nodes-int-res
      - TASK:
          script:
            #- SET
            #- GIT_SSH_COMMAND='ssh -i $SSHINTRES_PRIVATE_KEY_PATH' git clone git@github.com:ankul-shippable/sample_node.git && ls
            - echo ================ docker-int-res ==================
            - shipctl get_integration_resource_keys "docker-int-res"
            - shipctl get_integration_resource_field "docker-int-res" "url"
            - echo ================ ssh-int-res ==================
            - shipctl get_integration_resource_keys ssh-int-res
            - shipctl get_integration_resource_field ssh-int-res publicKey
            - shipctl get_integration_resource_field ssh-int-res privateKey
            - echo ================ nodes-int-res ==================
            - shipctl get_integration_resource_keys nodes-int-res
            - shipctl get_integration_resource_field nodes-int-res nodes
            - echo ================ key-value-int-res ==================
            - shipctl get_integration_resource_keys key-value-int-res
            - shipctl get_integration_resource_field key-value-int-res SOME_RANDOM_ENV_2
