jobs:
  - name: runSh-Job
    type: runSh
    steps:
      - TASK:
        - script: sudo apt-get install tree
        - script: tree -F IN
        - script: sleep 3
    on_success:
      - script: echo "successfully completed"
      - NOTIFY: slack-notifications

  - name: sample_java_runCI
    type: runCI
    steps:
      - IN: runSh-Job
    on_success:
      - script: echo "successfully completed"
      - NOTIFY: slack-notifications
