language: node_js

node_js:
  - 4.8.7

runtime:
  nodePool: default_cluster


build:
  ci:
    - echo true1
    - printenv

integrations:
  notifications: 
    - integrationName: email
      type: email
      recipients:
        - ankul@shippable.com
      on_success: always

#  hub:
#    - integrationName: docker-shared-subint
#      type: dockerRegistryLogin
#  generic:
#    - integrationName: kv-shared-subint   

resources:
  - name: pem-res
    type: integration
    integration: "pem-subint" 
    
  - name: ssh-res
    type: integration
    integration: "ssh-subint"     

jobs:
  - name: runSh-job
    type: runSh
    runtime:
      nodePool: default_cluster
    steps:
      - IN: pem-res
      - IN: ssh-res
      - TASK:
          script:
            - printenv
            - cat $PEMRES_KEYPATH
   
