language: node_js

node_js:
  - 4.8.7

#runtime:
#  nodePool: default_cluster

env:
  matrix:
    - ENV1: "foo1"
      ENV2: "moo1"
    - ENV1: "foo2"
      ENV2: "moo2"
    - ENV1: "foo3"
      ENV2: "moo3"
    - ENV1: "foo4"
      ENV2: "moo4"

build:
  ci:
    - echo true

resources:
  - name: nginx-image
    type: image
    integration: "docker-subint"
    pointer:
      sourceName: "ankul/app"
    seed:
      versionName: latest

  - name: nginx-image-2
    type: image
    integration: "docker-subint"
    pointer:
      sourceName: "ankul/app"
    seed:
      versionName: latest

jobs:
  - name: manifest-job
    type: manifest
    steps:
      - IN: nginx-image

#  - name: string_ints
#    type: runSh
#    integrations: easdssadas
#    steps:
#      - IN: nginx-image
#      - IN: manifest-job
#      - TASK:
#          script:
#            - printenv

#  - name: object_ints
#    type: runSh
#    integrations:
#      random: key
#      array: value
#    steps:
#      - IN: nginx-image
#      - IN: manifest-job
#      - TASK:
#          script:
#            - printenv

  - name: all_invalid_ints
    type: runSh
    runtime:
      nodePool: shared_one
    integrations:
      - all_invalid_ints_invalid_int_1
      - all_invalid_ints_invalid_int_2
    steps:
      - IN: nginx-image
      - IN: manifest-job
      - TASK:
          script:
            - printenv
            - random_1_8

  - name: some_invalid_ints
    type: runSh
    runtime:
      nodePool: shared_one
    integrations:
      - github-subint
      - some_invalid_ints_invalid_int_1
    steps:
      - IN: nginx-image
      - IN: manifest-job
      - TASK:
          script:
            - printenv

  - name: all_valid_ints
    type: runSh
    runtime:
      nodePool: shared_one
    integrations:
      - github-subint
      - docker-subint
    steps:
      - IN: nginx-image
      - IN: manifest-job
      - TASK:
          script:
            - printenv

  - name: runSh_with_image
    type: runSh
    runtime:
      nodePool: shared_one
    steps:
      - IN: nginx-image
      - TASK:
          script:
            - printenv

  - name: no_ints
    type: runSh
    runtime:
      nodePool: shared_one
    steps:
      - IN: nginx-image
      - IN: manifest-job
      - TASK:
          script:
            - printenv
